"use strict";
(function () {
    var avenger = 123;
    var exist;
    var power;
    var avengerr = 123;
    var existt;
    var powerr;
    avengerr = 'dr stone';
    console.log(avengerr.charAt(0));
    avengerr = 125.255635;
    console.log(avengerr.toFixed(2));
    console.log(existt);
    console.log(power);
    var avengerrr;
    var existtt;
    var powerrr;
    avengerrr = 'dr stone';
    console.log(avengerrr.charAt(0));
    avengerrr = 125.255635;
    console.log(avengerrr.toFixed(2));
    console.log(existtt);
    console.log(powerrr);
    var avengerrrr;
    var existttt;
    var powerrrr;
    avengerrrr = 'dr stone';
    console.log(avengerrrr.charAt(0));
    avengerrrr = 125.255635;
    console.log(avengerrrr.toFixed(2));
    console.log(existttt);
    console.log(powerrrr);
    var avengerrrrr = 123;
    var existtttt;
    var powerrrrr;
    avengerrrrr = 'dr stone';
    console.log(avengerrrrr.charAt(0));
    console.log(avengerrrrr(0));
    avengerrrrr = 125.255635;
    console.log(avengerrrrr.toFixed(2));
    console.log(existtttt);
    console.log(powerrrrr);
})();
//# sourceMappingURL=any.js.map